pipelines:
    default:
        -   step:
                name: Check Code Style
                image: nofutur3/php-component:8.0
                caches:
                    - composer
                script:
                    - composer install --no-interaction
                    - composer cs-check
        -   parallel:
                -   step:
                        name: PHP 5.3
                        image: nofutur3/php-component:5.3
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction

                            # tests
                            - composer test
                -   step:
                        name: PHP 5.5
                        image: nofutur3/php-component:5.5
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction

                            # tests
                            - composer test
                -   step:
                        name: PHP 5.6
                        image: nofutur3/php-component:5.6
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction

                            # tests
                            - composer test
                -   step:
                        name: PHP 7.0
                        image: nofutur3/php-component:7.0
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction

                            # tests
                            - composer test

                -   step:
                        name: PHP 7.1
                        image: nofutur3/php-component:7.1
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction
                            # phpstan has to be added in pipeline bc it requires PHP 7.1+
                            - composer require phpstan/phpstan --dev --no-interaction

                            # stan
                            - composer stan7

                            # tests
                            - composer test
                -   step:
                        name: PHP 7.2
                        image: nofutur3/php-component:7.2
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction
                            # phpstan has to be added in pipeline bc it requires PHP 7.1+
                            - composer require phpstan/phpstan --dev --no-interaction

                            # stan
                            - composer stan7

                            # tests
                            - composer test
                -   step:
                        name: PHP 7.3
                        image: nofutur3/php-component:7.3
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction
                            # phpstan has to be added in pipeline bc it requires PHP 7.1+
                            - composer require phpstan/phpstan --dev --no-interaction

                            # stan
                            - composer stan7

                            # tests
                            - composer test

                -   step:
                        name: PHP 7.4
                        image: nofutur3/php-component:7.4
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction
                            # phpstan has to be added in pipeline bc it requires PHP 7.1+
                            - composer require phpstan/phpstan --dev --no-interaction

                            # stan
                            - composer stan7

                            # tests
                            - composer test
                -   step:
                        name: PHP 8.0
                        image: nofutur3/php-component:8.0
                        caches:
                            - composer
                        script:
                            # Install composer dependencies
                            - composer install --no-interaction
                            # phpstan has to be added in pipeline bc it requires PHP 7.1+
                            - composer require phpstan/phpstan --dev --no-interaction
                            # old phpunit compatibility for php 8
                            - composer require christiaanbye/polyfill-each --dev --no-interaction

                            # stan
                            - composer stan

                            # tests
                            - composer test
