name: CI

on:
    push:
        branches:
            - "**"

jobs:
    php-tests:
        name: php ${{ matrix.php-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none
                    extensions: mbstring, intl, curl

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Run static analysis
                run: composer stan

            -   name: Start mock server
                run: docker run -d -p 1080:1080 mockserver/mockserver

            -   name: Wait for MockServer
                run: |
                    for i in {1..20}; do
                      if curl -s http://localhost:1080/status > /dev/null; then
                        echo "MockServer is ready"
                        exit 0
                      fi
                      echo "Waiting for MockServer..."
                      sleep 1
                    done
                    echo "MockServer did not start in time"
                    exit 1

            -   name: Create mock server from our production OpenAPI
                run: curl -X PUT -d "{\"specUrlOrPayload\":\"https://gate.thepay.cz/openapi.yaml\"}" http://localhost:1080/mockserver/openapi

            -   name: Run tests
                run: composer test

    php-with-psr-tests:
        name: php ${{ matrix.php-version }} psr/http-message ${{ matrix.psr-http-message-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.2']
                psr-http-message-version: ['1.0', '2.0']

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none
                    extensions: mbstring, intl, curl

            -   name: Install dependencies
                run: composer update --no-interaction --with psr/http-message:^${{ matrix.psr-http-message-version }}

            -   name: Run static analysis
                run: composer stan

            -   name: Start mock server
                run: docker run -d -p 1080:1080 mockserver/mockserver

            -   name: Wait for MockServer
                run: |
                    for i in {1..20}; do
                      if curl -s http://localhost:1080/status > /dev/null; then
                        echo "MockServer is ready"
                        exit 0
                      fi
                      echo "Waiting for MockServer..."
                      sleep 1
                    done
                    echo "MockServer did not start in time"
                    exit 1

            -   name: Create mock server from our production OpenAPI
                run: curl -X PUT -d "{\"specUrlOrPayload\":\"https://gate.thepay.cz/openapi.yaml\"}" http://localhost:1080/mockserver/openapi

            -   name: Run tests
                run: composer test

    npm:
        name: "npm"
        runs-on: ubuntu-latest
        container: "node"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Install dependencies
                run: npm install

            -   name: Run tests
                run: npm test
