name: CI

on:
    push:
        branches:
            - "**"

jobs:
    php83:
        name: "php 8.3"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.3"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install dependencies
                run: composer install

            -   name: Run static analysis
                run: composer stan

            -   name: Run tests
                run: composer test

    php82:
        name: "php 8.2 psr/http-message 2.0"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.2"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: composer update --no-interaction --with psr/http-message:^2.0

            -   name: Check code style
                run: composer cs-check

            -   name: Run static analysis
                run: composer stan

            -   name: Run tests
                run: composer test

    php82psrmessage10:
        name: "php 8.2 psr/http-message 1.0"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.2"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: composer update --no-interaction --with psr/http-message:^1.0

            -   name: Run static analysis
                run: composer stan

            -   name: Run tests
                run: composer test

    php81:
        name: "php 8.1"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.1"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: composer install --no-interaction

            - name: Run static analysis
              run: composer stan

            - name: Run tests
              run: composer test

    php80:
        name: "php 8.0"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.0"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: composer install --no-interaction

            - name: Run static analysis
              run: composer stan

            - name: Run tests
              run: composer test

    php74:
        name: "php 7.4"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.4"
        steps:
            # Deprecation example for future support removal.
            #
            #-   name: Deprecation check (2023-01-01T00:00:00+01:00)
            #    run: if [ "$(date +%s)" -gt "1672527600" ]; then echo "This PHP version support ended"; exit1; else echo "Deprecation OK"; fi

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Run static analysis
                run: composer stan

            -   name: Run tests
                run: composer test

    npm:
        name: "npm"
        runs-on: ubuntu-latest
        container: "node"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: npm install

            -   name: Run tests
                run: npm test
