name: CI

on:
    push:
        branches:
            - "*"

jobs:
    php81:
        name: "php 8.1"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.1"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: composer install --no-interaction
            - name: Phpstan has to be added in pipeline bc it requires PHP 7.1+
              run: composer require phpstan/phpstan --dev --no-interaction
            - name: Old phpunit compatibility for php 8
              run: composer require christiaanbye/polyfill-each --dev --no-interaction

            - name: Check code style
              run: composer cs-check

            - name: Run static analysis
              run: composer stan

            - name: Run tests
              run: composer test81

    php80:
        name: "php 8.0"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.0"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: composer install --no-interaction
            - name: Phpstan has to be added in pipeline bc it requires PHP 7.1+
              run: composer require phpstan/phpstan --dev --no-interaction
            - name: Old phpunit compatibility for php 8
              run: composer require christiaanbye/polyfill-each --dev --no-interaction

            - name: Check code style
              run: composer cs-check

            - name: Run static analysis
              run: composer stan

            - name: Run tests
              run: composer test

    php74:
        name: "php 7.4"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.4"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction
            -   name: Phpstan has to be added in pipeline bc it requires PHP 7.1+
                run: composer require phpstan/phpstan --dev --no-interaction

            -   name: Run static analysis
                run: composer stan7

            -   name: Run tests
                run: composer test

    php73:
        name: "php 7.3"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.3"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction
            -   name: Phpstan has to be added in pipeline bc it requires PHP 7.1+
                run: composer require phpstan/phpstan --dev --no-interaction

            -   name: Run static analysis
                run: composer stan7

            -   name: Run tests
                run: composer test

    php72:
        name: "php 7.2"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.2"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction
            -   name: Phpstan has to be added in pipeline bc it requires PHP 7.1+
                run: composer require phpstan/phpstan --dev --no-interaction

            -   name: Run static analysis
                run: composer stan7

            -   name: Run tests
                run: composer test

    php71:
        name: "php 7.1"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.1"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction
            -   name: Phpstan has to be added in pipeline bc it requires PHP 7.1+
                run: composer require phpstan/phpstan --dev --no-interaction

            -   name: Run static analysis
                run: composer stan7

            -   name: Run tests
                run: composer test

    php70:
        name: "php 7.0"
        runs-on: ubuntu-latest
        container: "nofutur3/php-component:7.0"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Run tests
                run: composer test

    php56:
        name: "php 5.6"
        runs-on: ubuntu-latest
        container: "nofutur3/php-component:5.6"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction
                env:
                    COMPOSER_MEMORY_LIMIT: -1

            -   name: Run tests
                run: composer test

    php55:
        name: "php 5.5"
        runs-on: ubuntu-latest
        container: "nofutur3/php-component:5.5"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction
                env:
                    COMPOSER_MEMORY_LIMIT: -1

            -   name: Run tests
                run: composer test

    php53:
        name: "php 5.3"
        runs-on: ubuntu-latest
        container: "nofutur3/php-component:5.3"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Run tests
                run: composer test
