name: CI

on:
    push:
        branches:
            - "**"

jobs:
    php-tests:
        name: php ${{ matrix.php-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.4', '8.0', '8.1', '8.3', '8.4', '8.5']

        steps:
            -   name: Start mock server
                run: docker run -d -p 1080:1080 mockserver/mockserver

            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none
                    extensions: mbstring, intl, curl

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Check code style (PHP 8.5)
                if: matrix.php-version == '8.5'
                run: composer cs-check

            -   name: Run static analysis
                run: composer stan

            -   name: Create mock server from our production OpenAPI
                run: curl -X PUT -d "{\"specUrlOrPayload\":\"https://gate.thepay.cz/openapi.yaml\"}" http://localhost:1080/mockserver/openapi

            -   name: Run tests
                run: composer test


    php-with-packages-tests:
        name: >
            php ${{ matrix.php-version }}
            egulias/email-validator ${{ matrix.egulias-email-validator }}
            psr/http-message ${{ matrix.psr-http-message-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                # platform
                php-version: ['8.2']
                # packages
                egulias-email-validator: ['3.2', '4.0']
                psr-http-message-version: ['1.0', '2.0']

        steps:
            -   name: Start mock server
                run: docker run -d -p 1080:1080 mockserver/mockserver

            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none
                    extensions: mbstring, intl, curl

            -   name: Install dependencies
                run: >
                    composer update --no-interaction
                    --with egulias/email-validator:^${{ matrix.egulias-email-validator }}
                    --with psr/http-message:^${{ matrix.psr-http-message-version }}

            -   name: Run static analysis
                run: composer stan

            -   name: Create mock server from our production OpenAPI
                run: curl -X PUT -d "{\"specUrlOrPayload\":\"https://gate.thepay.cz/openapi.yaml\"}" http://localhost:1080/mockserver/openapi

            -   name: Run tests
                run: composer test

    npm:
        name: "npm"
        runs-on: ubuntu-latest
        container: "node"
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Install dependencies
                run: npm install

            -   name: Run tests
                run: npm test
